"""Generate a .docx literature review from a LitReviewResult."""
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from ..llm.litreview import LitReviewResult


def write_litreview_docx(result: LitReviewResult, output_path: Path) -> None:
    doc = Document()

    # ── Page margins ──────────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin = Pt(72)
        section.bottom_margin = Pt(72)
        section.left_margin = Pt(90)
        section.right_margin = Pt(90)

    # ── Title ─────────────────────────────────────────────────────────────
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(f"Literature Review: {result.topic}")
    title_run.bold = True
    title_run.font.size = Pt(18)

    subtitle_para = doc.add_paragraph()
    subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle_para.add_run(
        f"Generated by MAVYN  ·  {datetime.now().strftime('%B %d, %Y')}"
    )
    subtitle_run.font.size = Pt(11)
    subtitle_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # ── Introduction ──────────────────────────────────────────────────────
    _add_heading(doc, "1. Introduction")
    _add_body(doc, result.introduction)

    # ── Theme sections ────────────────────────────────────────────────────
    for i, theme in enumerate(result.themes, 2):
        _add_heading(doc, f"{i}. {theme['name']}")
        _add_body(doc, result.theme_sections.get(theme["name"], ""))

    # ── Research gaps ─────────────────────────────────────────────────────
    gap_num = len(result.themes) + 2
    _add_heading(doc, f"{gap_num}. Research Gaps and Future Directions")
    _add_body(doc, result.gaps)

    # ── Conclusion ────────────────────────────────────────────────────────
    conc_num = gap_num + 1
    _add_heading(doc, f"{conc_num}. Conclusion")
    _add_body(doc, result.conclusion)

    # ── References ────────────────────────────────────────────────────────
    _add_heading(doc, "References")
    for s in result.paper_summaries:
        ref_para = doc.add_paragraph(style="List Number")
        ref_run = ref_para.add_run(f"{s['authors']} ({s['year']}). {s['title']}.")
        ref_run.font.size = Pt(10)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))


def _add_heading(doc: Document, text: str) -> None:
    para = doc.add_heading(text, level=1)
    para.runs[0].font.size = Pt(13)
    para.runs[0].font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)


def _add_body(doc: Document, text: str) -> None:
    if not text:
        return
    for paragraph in text.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            p = doc.add_paragraph(paragraph)
            p.paragraph_format.space_after = Pt(8)
            for run in p.runs:
                run.font.size = Pt(11)
